config/routes.rb
MitakalabTwitter::Application.routes.draw do

  root 'users#index'

  get 'signup' => 'users#new', as: :signup
  get 'signin' => 'sessions#new', as: :signin
  get 'signout' => 'sessions#destroy', as: :signout

  resources :users
  resources :sessions
  resources :tweets

  

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tweets

  has_secure_password
  
  has_attached_file :avatar, {
    :styles => {
      :thumb => ["50x50#", :png],
      :medium => ["100x100#", :png],
      :large => ["300x300>", :png]
    },
    :convert_options => {
      :thumb => "-gravity Center -crop 50x50+0+0",
      :thumb => "-gravity Center -crop 100x100+0+0",
    }
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to signin_path if current_user.nil?
  end

  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user
    else
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authorize, :only => [:new, :create, :edit, :update, :destroy]

  def index
    @tweets = Tweet.all
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user
    @tweet.save
    redirect_to @tweet
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    @tweet.update(tweet_params)
    redirect_to @tweet
  end

  private
  def tweet_params
    params.require(:tweet).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: [:edit, :update, :destroy]

  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to @user
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MitakalabTwitter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  <%= link_to current_user.username, current_user %>
  <%= link_to "Sign out", signout_path %>
<% else %>
  <%= link_to "Sign in", signin_path %>
  <%= link_to "Sign up", signup_path %>
<% end %>

<%= yield %>

</body>
</html>

app/views/tweets/_form.html.erb
<div class="form">
  <%= form_for @tweet do |f| %>
  <div class="content">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>
  <div class="submit">
    <%= f.submit %>
  </div>
  <% end %>
</div>

app/views/tweets/_tweet.html.erb
<div class="tweet">
  <div class="content">
    <%= tweet.content %>
  </div>
  <div class="username">
    <%= tweet.user.username %>
  </div>
</div>

app/views/tweets/edit.html.erb
<%= render 'form' %>

app/views/tweets/index.html.erb
<div id="tweets-index">
  <div class="tweets">
    <% @tweets.each do |tweet| %>
      <%= render 'tweet', :tweet => tweet %>
      <%= link_to 'show', tweet %>
    <% end %>
  </div>
</div>

app/views/tweets/new.html.erb
<%= render 'form' %>

app/views/tweets/show.html.erb
<div class="tweets-show">
  <%= render 'tweet', :tweet => @tweet %>
  <%= link_to 'edit', edit_tweet_path(@tweet) %>
</div>

app/views/users/edit.html.erb
<div id="users-edit">
  <div class="form">
    <%= form_for @user do |f| %>
    <div class="avatar">
      <%= f.label :avatar %>
      <%= f.file_field :avatar %>
    </div>
    <div class="submit">
      <%= f.submit %>
    </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div id="users-new">
  <div class="form">
    <%= form_for @user do |f| %>
    <div class="username">
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>
    <div class="password">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class="password_confirmation">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="submit">
      <%= f.submit %>
    </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div id="users-show">
  <div class="username">
    <%= @user.username %>
  </div>
  <div class="avatar">
    <%= image_tag @user.avatar(:medium) %>
  </div>
</div>